### ISSUE TITLE
Bugs - session_start() and undefined $dg variable in server error.log

### ISSUE THREAD

**Issue by tobias992** [adminerevo/adminerevo#23] opened 2023-07-07 21:23 UTC
Hello,

First of all, thank you for your work on this fork. I've been using Adminer for many years and it's really sad that the original version is no longer supported. Is there any way to support your work?

With the current original version of adminer, I get hundreds of log lines in server error.log. I checked your commits and didn't see anything about this. So maybe you can fix these problems in the next releases of your version?

`2023/07/07 00:55:08 [error] 1569199#1569199: *2613661 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): Session cache limiter cannot be sent after headers have already been sent (output started at /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php:683) in /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php on line 72" while reading upstream, client: 185.209.196.145, server: mysite.com, request: "GET /wms-adminer-6450fd65cc2742f7.php?username=dbuser123&db=dbname123&dump= HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-mysite-81.sock:", host: "mysite.com", referrer: "https://mysite.com/wms-adminer-6450fd65cc2742f7.php?username=dbuser123&db=dbname123&edit=xxxxx"`

`2023/07/07 00:55:08 [error] 1569199#1569199: *2613661 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $dg in /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php on line 868PHP message: PHP Warning:  Undefined variable $dg in /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php on line 868PHP message: PHP Warning:  Undefined variable $dg in /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php on line 868PHP message: PHP Warning:  Undefined variable $dg in /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php on line 868PHP message: PHP Warning:  Undefined variable $dg in /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php on line 868PHP message: PHP Warning:  Undefined variable $dg in /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php on line 868PHP message: PHP Warning:  Undefined variable $dg in /home/mysite/html/docs/wms-adminer-6450fd65cc2742f7.php on line 868" while reading response header from upstream, client: 185.209.196.145, server: mysite.com, request: "GET /wms-adminer-6450fd65cc2742f7.php?username=dbuser123&db=dbname123&script=db HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-mysite-81.sock:", host: "mysite.com", referrer: "https://mysite.com/wms-adminer-6450fd65cc2742f7.php?username=dbuser123&db=dbname123&dump="`

**Comment by LionelLaffineur** [comment] 2023-07-10 14:35
Hi @tobias992,
We are also a small group of users of Adminer sad that it is not maintained and not wiling to migrate to another tool ...
Thanks for the interest you have in AdminEvo, which I hope, will continue for a long time !

Could you give a little of context about the error you report here ?  Because on both the production version we use (latest stable) and the development one we are working onto, we don't get that (kind of) error.

Regards,
L.

P.S.: we have not yet setup anything for supporting us, we are starting for a short time only.  Right now, if you would like to answer polls and do some testing of the development version, it would be very helpful to us.

**Comment by LionelLaffineur** [comment] 2023-07-10 15:32
I think a very good way to test is to use the development version on your daily business and report any issue you would encounter.  Nothing special to do, your daily work is the best test for an upcoming release !

**Comment by tobias992** [comment] 2023-07-10 15:37
I already use your actual main branch. Maybe it's not fully PHP 8.0 compatible?

Finally your version is working - i just have hundreds of loglines errors in server error.log.

**Comment by LionelLaffineur** [comment] 2023-07-10 15:37
If you would like to better understand the error reported here above, I would suggest you to take the complete branch and use "adminer/index.php".  That is the source code, where code / variables names will not be scrambled to reduce the size of the single PHP file of the production.

**Comment by LionelLaffineur** [comment] 2023-07-10 15:38
> I already use your actual main branch. Maybe it's not fully PHP 8.0 compatible?
> 
> Finally your version is working - i just have hundreds of loglines errors in server error.log.

I'm developing / testing with PHP 8.1.

**Comment by tobias992** [comment] 2023-07-10 15:44
OK understand. Now i test the complete branch, hopefully this error message helps more.

`2023/07/10 17:41:18 [error] 1733712#1733712: *1823597 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $sql in /home/siteabc/html/docs/adminerevo/adminer/script.inc.php on line 15PHP message: PHP Warning:  Undefined variable $sql in /home/siteabc/html/docs/adminerevo/adminer/script.inc.php on line 15" while reading upstream`

**Comment by LionelLaffineur** [comment] 2023-07-10 19:26
OK, I see the problem.  I'll make sure it is fixed for the next release !

**Comment by LionelLaffineur** [comment] 2023-07-10 20:21
Would you be so kind to test the branch "fix-undefined-variable" onto your setup and let me know if the issue is fixed ?
(and if I didn't introduce any side effect)

**Comment by tobias992** [comment] 2023-07-10 20:32
Looks fine. I tested the complete branch and also the compiled version (without submodules).

Thank you :)

**Comment by LionelLaffineur** [comment] 2023-07-11 11:25
Branch merged to main, will be part of the next release.

**Closed by LionelLaffineur** 2023-07-11 11:25 UTC
